name: Eleventy Deploy

on:
  push:
    branches:
    - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Install
        run: npm install
      - name: Build
        run: npx @11ty/eleventy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
            publish_dir: _site
            publish_branch: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
